### ISSUE TITLE
Determining the stack (CMS) for BTCPay Server's blog

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/blog#1]
As most of you know, BTCPay Server as an open-source software tends to have everything - open-sourced. Besides software itself we've done great job opening our main [website](btcpayserver.org/), [documentation](docs.btcpayserver.org/), [directory ](https://directory.btcpayserver.org/)and even an entire community [infrastructure](https://github.com/btcpayserver/btcpayserver-infra/). 

The only thing we don't have on GitHub is[ our blog. ](https://blog.btcpayserver.org/) Even though our blog is on the infra itself, the only way to access and contribute to it is by having an access to the back-end. Currently, blog is powered by CMS (content management system) called WordPress, which is probably the most popular blogging software today. WordPress itself is open-source software, but it can sometimes get clunky and with each release it seems to grow in its robustness.

I'm opening this issue, because I'd like to start a discussion on how we can have btcpay server blog on GitHub. The main goal of open-sourcing the blog, besides transparency is to allow people to easier contribute with the content from GitHub and content planning and management easier with GitHub issues.

However, most of writers don't know markdown and GitHub. They are not as tech savvy, so that opens a whole set new can of worms.

### Pros of putting the blog on GitHub

- Encouraging  contributions 
- Easier collaboration and management on a well-established platform
- Transparency
- Our SEO currently is non-existent so any negative SEO impact due to migration is better done at this stage

### Cons of putting a blog on Github
- Writers may still prefer a text editor to markdown
- It will take time to determine best software/stack/approach
- Migration can be painful and can cause bad impact for SEO if not handled properly

### Suggested solutions

1. Leave things the way they are and improve the look of the current blog
2. Use VuePress stack  (which we use for docs) 
3. Wordpress + GitHub?
4. Ghost + GitHub?

#### Leaving things the way they are
Pros:

- Little effort in improving the styling
- No negative SEO impact

Cons:

- People can't contribute from GitHub
- Blog contribution remain behind closed doors
- WordPress is notorious for poor security

#### VuePress 

Pros: 

- Same stack so devs will be familiar with it
- Easy to standardize design guidelines

Cons:

- Will take quite a bit of dev time
- VuePress does not seem to be as SEO friendly as CMS
- Possible negative SEO impact if migration isn't done properly

#### WordPress + GitHub
Pros:
- Minimum SEO and migration impact

Cons:

- It will take time to find a proper solution
- All negative side-effects of WordPress still remain

#### Ghost+ GitHub

Pros:

- Great editor for people writing on the back end
- Database can be on a VPS to allow people to contribute on the front-end and back-end
- Out of the box SEO and decent design
- There are a few well-documented tutorials and approaches

Cons:

- Will take time to develop custom theme
- Possible negative SEO due to migration

I outlined some ideas and pros and cons in my view, I'm hoping to start a discussion where we can brainstorm approaches. If you know any other approach or have something to add to my Pros/Cons list please write a comment. 

It will take time to figure the process out and depending on the approach we take to implement it, so it's important to make an informed decision. Note that some pros/cons may be biassed since I may be familiar with one approach more than the other.

**Comment by Zaxounette** [comment]
I'm not able to comment on the technicalities of the different proposed solutions, but here's my 2 sats on some stuff:

> However, most of writers don't know markdown and GitHub. They are not as tech savvy, so that opens a whole set new can of worms.

Setting up a Github account and managing it might be too much for a few writers, but for the large majority, it's not that complicated.
As for Markdown, it's just a matter of a few days of adapting to it, it's really not complicated.

New contributors can also ask for assistance in the early days, while they get accustomed to those processes.

----
> Possible negative SEO due to migration

Of what I understood from the SEO coming from the blog, it's not an enormous viewership for the time being.

The possible negative SEO would only have a very limited impact, so we could maybe consider it a non-issue for the purpose of this migration ? Thus deleting a possible `con` for easier decision-making ?

----
Lastly, I really like what you have been setting up the last months: Everything in Github for transparency. I'd vote for a solution that makes that possible for the blog as well.

**Comment by pavlenex** [comment]
I'll go ahead and close this issue for now. As decided on an SEO meeting, let's stick with WordPress for another year and meanwhile try to find a way to sync content between GitHub and WordPress so that collaboration and reviews can happen on GitHub.
