### ISSUE TITLE
Warnings in the header

### ISSUE THREAD

**Issue by bitpaint** [btcpayserver/blog#6]
Hey guys, something went wrong here:

(tested with Firefox & Tor Browser)

```
 Warning: Use of undefined constant CHILD_THEME_HANDLE - assumed 'CHILD_THEME_HANDLE' (this will throw an Error in a future version of PHP) in /var/www/html/wp-content/themes/genesis-sample/lib/output.php on line 150

Warning: Use of undefined constant CHILD_THEME_HANDLE - assumed 'CHILD_THEME_HANDLE' (this will throw an Error in a future version of PHP) in /var/www/html/wp-content/themes/genesis-sample/lib/gutenberg/init.php on line 22

Warning: Use of undefined constant CHILD_THEME_HANDLE - assumed 'CHILD_THEME_HANDLE' (this will throw an Error in a future version of PHP) in /var/www/html/wp-content/themes/genesis-sample/lib/gutenberg/inline-styles.php on line 49

```

![image](https://user-images.githubusercontent.com/67663265/124678998-f8420f80-dec3-11eb-9ad8-d793c9999bac.png)

**Comment by dennisreimann** [comment]
Yes, we are also in the process of redoing the blog (see #5) and will hopefully replace the current version soon. /cc @Kukks

**Comment by Kukks** [comment]
Can we avoid fixing this? I'm terrified of touching the blog code as last time it went rogue and locked us all out.

**Comment by activefog** [comment]
Hoping to have the new blog ready this week, if you all are OK with leaving the wordpress bug for that long.

**Comment by Zaxounette** [comment]
> Hoping to have the new blog ready this week, if you all are OK with leaving the wordpress bug for that long.

No objection to this on my side.

**Comment by dennisreimann** [comment]
Yup, let's not put any more effort into the old one and rather focus on launching the new baby :)
